services:
  api:
    build:
      context: ./
    container_name: api
    ports:
      - "8080:8080"
    environment:
      - OLLAMA_MODEL=tinyllama
    networks:
      - ollama-net

networks:
  ollama-net:
    external: true
