services:
  ollama:
    image: alpine/llama3.2
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - data:/root/.ollama
    networks:
      - ollama-net

volumes:
  data:

networks:
  ollama-net:
    external: true
